apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: parte2
  labels:
    app: flask-api
spec:
  type: NodePort
  selector:
    app: flask-api
  ports:
    - name: http
      port: 8080        # puerto del servicio dentro del cluster
      targetPort: 5000  # puerto del contenedor Flask
