apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: parte2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: inventorfer/flask-postgres-compose:1.0   # tu imagen
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
